### ISSUE TITLE
Make favicon less crappy for the admin panel

### ISSUE THREAD

**Issue by ryananeff** [ehhop/ehhapp-twilio#13]
How did you do the EHHAPP favicons to be so nice when you bookmark the app and how do we do the same?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/95571136199190/95571147705556)

**Comment by ryananeff** [comment]
Not complete yet. I'll fix this when I have the leisure time. Or you can pass it on to anyone who wants to have some fun with graphic design.

[--- Commented from Asana.com
#commenter Kevin Hu
---[aa]

**Comment by ryananeff** [comment]
I would definitely say it's low-priority. also, this is more of an issue of the iOS/Android bookmarklet than the favicon as you mentioned

**Comment by hukevinxiaochen** [comment]
See 9a61c265d
