### ISSUE TITLE
Encrypt config.py and keep master password off server

### ISSUE THREAD

**Issue by ryananeff** [ehhop/ehhapp-twilio#20]
could be a different way of securing this, not sure what the level of paranoia we need to take is.

Restarts of the server should require decrypting passwords using a master password kept off of the server OR a keypair like gpg that a user would have to input. Variables should then be stored in memory somewhere secure like in Python in memory variables. Entering the master password should not be automated but should be set up to immediately notify whoever is responsible for doing that.

This way even with a complete copy of all files on droplet there is no possible way to decrypt data unless memory was dumped somehow.

TODO: Reliability, how to keep this simple

**Comment by ryananeff** [comment]
Also thinking of using this: https://pypi.python.org/pypi/keyring

**Comment by hukevinxiaochen** [comment]
Interesting... Just some extra reading links for myself I'm going to drop here if anyone else is interested.

[secretstorage](https://pypi.python.org/pypi/SecretStorage)
[Secret Service](https://specifications.freedesktop.org/secret-service/index.html)

**Comment by ryananeff** [comment]
Implemented as of 3/15/16
