### ISSUE TITLE
Hardcode the package name into initialization of Flask app

### ISSUE THREAD

**Issue by hukevinxiaochen** [ehhop/ehhapp-twilio#31]
This is completely non-urgent. Just putting it here to make sure I don't forget to revisit this question later.

We initialize Flask as follows:

`app = Flask(__name__)`

Should we do as is said in the Flask API docs? And go with

`app = Flask("ehhapp_twilio")`

instead?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/95571136199190/149085493057328)

**Comment by ryananeff** [comment]
Not really sure why to put the name, interesting find!
