### ISSUE TITLE
In __init__.py, where is sqlalchemy_db defined?

### ISSUE THREAD

**Issue by hukevinxiaochen** [ehhop/ehhapp-twilio#32]
See 15c57f

We **init**.py but,

`app.config['SQLALCHEMY_DATABASE_URI'] = sqlalchemy_db`

where is sqlalchemy_db defined? Is it made available as a global?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/95571136199190/149092625743659)

**Comment by ryananeff** [comment]
in ehhapp-twilio/ehhapp_twilio/database.py

**Comment by hukevinxiaochen** [comment]
Still confused. How and where is the name `sqlalchemy_db` defined? database.py only imports flask_sqlalchemy and assigns `db = SQLAlchemy(app)`. Maybe it is in the config on box?

**Comment by ryananeff** [comment]
Oh I see what you mean. Yeah it's on Box. Neat huh?

**Comment by hukevinxiaochen** [comment]
Very!

Kevin Hu, MS4, Icahn School of Medicine at Mount Sinai
Cell: 646-651-6517

_Co-Chair_, East Harlem Health Outreach Partnership (EHHOP)
http://eastharlemhealth.com
Support EHHOP http://ehhapp.org/AmazonAssociates by having 4-8% of your
next Amazon purchase go to EHHOP.

_Fellow_, Academic IT
Bluebook http://bluebook.mssm.edu App, ASM http://asmapp.mssm.edu App,
Orientation http://orientation.mssm.edu App

_Scholar_, Sinai AppLab
nodehealth.org, @DigMedEvidence https://twitter.com/DigMedevidence

**Comment by ryananeff** [comment]
See commit 2361738d for a rough listing
