### ISSUE TITLE
Review the assignment schedule routing code

### ISSUE THREAD

**Issue by ryananeff** [ehhop/ehhapp-twilio#45]
Seems like it is all of a sudden using a Sun-Sat schedule again instead of Wed-Wed

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/95571136199190/166736614196141)

**Comment by hukevinxiaochen** [comment]
Thanks Ryan!

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.1.9&pv=10.0.2&source=email_footer_2]
On Sun, Oct 2, 2016 at 12:54 PM, Ryan Neff notifications@github.com wrote:
Closed #45 [https://github.com/ehhop/ehhapp-twilio/issues/45] .
