### ISSUE TITLE
Extra spaces in the Google Drive schedule (or other blank characters) are preventing DB lookups

### ISSUE THREAD

**Issue by ryananeff** [ehhop/ehhapp-twilio#49]
Review this ASAP!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/95571136199190/190295093422197)

**Comment by hukevinxiaochen** [comment]
Got it!

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.1.9&pv=10.0.2&source=email_footer_2]
On Mon, Oct 3, 2016 at 3:00 PM, Ryan Neff notifications@github.com wrote:
Review this ASAP!

**Comment by ryananeff** [comment]
https://github.com/ehhop/ehhapp-twilio/commit/1c3991379bafbc0aef91f5bc3ea89aa88b422908 didn't fix it (from last week)

**Comment by ryananeff** [comment]
![image](https://cloud.githubusercontent.com/assets/1616888/19050347/2ef048fa-897c-11e6-9cec-4fbe8140aca7.png)

**Comment by hukevinxiaochen** [comment]
Attempted to re-input names manually in the Google Drive spreadsheet: https://docs.google.com/spreadsheets/d/1bGuP1jCmL5HcXJp0EHpnfRKsQ-6Tnx6keCgDpMhVY-k/edit#gid=7

and then used front-end test routes https://twilio.ehhapp.org/intents as confirmation of successful DB lookup.

However, results are still not as expected. Under Schedule On Call Medical TS there is an empty array where there should be `u'kevin.hu@icahn.mssm.edu'`

@nosarcasm Are you sure this is a whitespace issue?

**Comment by ryananeff** [comment]
https://github.com/ehhop/ehhapp-twilio/issues/30 Schedule lookup test not implemented

**Comment by ryananeff** [comment]
fixed
