### ISSUE TITLE
retrieve files from box using API not FTP

### ISSUE THREAD

**Issue by ryananeff** [ehhop/ehhapp-twilio#50]
FTP seems to not be supported properly by Box

**Comment by hukevinxiaochen** [comment]
@nosarcasm https://app.box.com/services/box_ftp_server

Box supports only passive FTP.

I don't know what this means, but ftplib provides some support for this.

For more on passive vs active FTP see http://www.jscape.com/blog/bid/80512/Active-v-s-Passive-FTP-Simplified

**Comment by hukevinxiaochen** [comment]
@nosarcasm Not a bad idea. Can you post a link to the relevant Box API pages you've been snooping around on?

**Comment by ryananeff** [comment]
Abandoning in favor of a different solutiuon
