### ISSUE TITLE
Spanish Recordings Re-record

### ISSUE THREAD

**Issue by caticrawford** [ehhop/ehhapp-twilio#7]
Hey @nosarcasm ,

Please send me and @meir01 the scripts for the spanish recordings. Thank you!!!

```
look we are
writing
code 
ahahaha cool
```

**Comment by ryananeff** [comment]
The audio files were actually checked in hahahaha

[here](https://github.com/ehhop/ehhapp-twilio/tree/master/assets/audio)

**Comment by hukevinxiaochen** [comment]
@meir01 @caticrawford should be able to find all the Spanish audio that needs to be recorded by seeing what is available in English and what's still missing for Spanish in the assets directory checked in to our repo because @nosarcasm thinks this is mediahub :stuck_out_tongue_closed_eyes: . Closing issue.

**Comment by caticrawford** [comment]
Is the idea that we would record what we hear in the files? Or is there a separate written script? When I try to play the audio files, they dont wory :-/

**Comment by ryananeff** [comment]
@caticrawford Try downloading the repo as a zip and opening them from there https://github.com/ehhop/ehhapp-twilio/archive/master.zip they're all in the assets/audio/ folder inside 

In terms of a written script, I just haven't gotten around to writing it out yet unfortunately but it's all in there.

@hukevinxiaochen...smh

**Comment by ryananeff** [comment]
Each line is it's own recording. The first two are already in spanish. Blanks are blank on the recording.
- Gracias por llamar a la Clinica de EHHOP. Para instrucciones en espanol, marque el numero 2. EHHOP es la Asociacion Comunitaria para la Salud de East Harlem en Mount Sinai. 
- Si esto es una emergencia, cuelgue el telefono y llame ahora al 9-1-1. 
- Listen carefully as our menu options have changed.
- If you know your party's extension, please press #.
- Please dial your four digit extension now.
- Taking you to the mailbox of ___
- We're sorry, but we couldn't find that extension at EHHOP.
- Connecting you with __
- If you have an appointment today, please press 1. If you have not been to EHHOP before, please press 2. If you are an EHHOP patient and have an urgent medical concern, please press 3. If you are an EHHOP patient and have a question about your medication or getting a prescription, please press 4. If you are an EHHOP patient and would like to schedule an appointment with a specialist, dental, or vision, please press 5. If you are an EHHOP patient and have a question about a bill you received, please press 6. For all other non-urgent concerns, please press 7. To hear this menu again, stay on the line.
- Please leave a message for us after the tone. Include your first name, last name, and date of birth, and let us know what times we can call you back.
- We will call you back as soon as possible.
- We will call you back within the next day.
- Your message was sent. Thank you for contacting EHHOP. Goodbye!
- You have pressed an incorrect key. Please try again.
- We're sorry, but your call may have been cut short.
- We're sorry, but our phone system is currently experiencing technical difficulties. Your call has been logged and we will call you back within one day. Please try your call again later.
- Thank you for contacting EHHOP. Goodbye!

other stuff:
- Hello. You have an important message from the EHHOP clinic. Press 1 to hear your message now.
- Please enter your date of birth, entering two digits for the month, day, and year. For instance, if your date of birth is july 1st, 1960, you would enter 07-01-60.
- We're sorry, but we couldn't understand the date of birth you entered. Please make sure that you enter two digits for the month before the day, and then the year. Please enter your date of birth now.
- Please wait to hear your secure message.

**Comment by caticrawford** [comment]
Thanks, Ryan! On it
